### ISSUE TITLE
Ver. 3.8.3.3 crashes with -t 3 for hodl algo

### ISSUE THREAD

**Issue by YetAnotherRussian** [JayDDee/cpuminer-opt#104]
**cpuminer-avx2 -a hodl -t 3 --cpu-affinity 7 -o stratum+tcp://hodl.suprnova.cc:4693 -u 123 -p 123**

Crash (stable) after ~5 seconds of mining (one share may even be accepted).

Ver.: 3.8.3.3 cpuminer-avx2.exe binary (yours from releases page)
CPU: i3-7350k
RAM: 16Gb
OS: Win 10

It's strangely, but no issues for:
cpuminer-avx2 -a hodl -t 2 --cpu-affinity 9
cpuminer-avx2 -a hodl -t 4 --cpu-affinity 15

**Comment by JayDDee** [comment]
Odd thread numbers should never be used for any algo. It's best to use powers of 2 as much as
possible. It's mostly a performance issue and load balancing. But Hodl is special, it requires it
because the threads work cooperatively on a shared buffer. Odd divisors mess it up.

When experimenting with non-default options don't be too quick to assume problems.

**Comment by YetAnotherRussian** [comment]
> Odd thread numbers should never be used for any algo
That's not gonna happen when "core/thread count" > "L3 size / n Mb" (cryptonight or cryptonight-lite) or core count is not multiple of 2. You forgot about "I need to work & mine" case as well.

This (bout hodl) may be added to readme or something...
