### ISSUE TITLE
8-bit immediate error

### ISSUE THREAD

**Issue by paperballs** [JayDDee/cpuminer-opt#111]
When running sudo make on ubuntu 16.04, I'm getting error message: the last argument must be an 8-bit immediate. I'm new to github, hopefully doing this right.

_mm_slli_sil28( lo, 16 - (n<<2) ) );

https://github.com/JayDDee/cpuminer-opt/blob/157508bd075e28020c642e3f824efc4c810f4863/algo/shavite/sph-shavite-aesni.c#L86

**Comment by JayDDee** [comment]
This is interesting. It compiles for me on Mint 18 (based on Ubuntu 16.04). It looks like the compiler is
complaining about the second argument being an expression instead of a simple variable. It shouldn't
matter. I'll need a lot more info to understand this, including your CPU and build procedure.

**Comment by JayDDee** [comment]
No follow up by author.
