### ISSUE TITLE
trojan:win32/skeeyah.a!rfn detected.

### ISSUE THREAD

**Issue by naviretlav** [JayDDee/cpuminer-opt#118]
Windows defender detects the "trojan:win32/skeeyah.a!rfn" in this and deletes the files. 
Can you confirm that this software is "clean" and fix this issue ?

**Comment by aaronsace** [comment]
#109 Please report to your virus checker as safe and add to your exceptions.

**Comment by naviretlav** [comment]
Google chrome also reports this windows build as unsafe

**Comment by aaronsace** [comment]
Same advice; it's not an issue with this software so no need to report it here.

**Comment by kameleon25** [comment]
Everyone will report it as a virus. Since every script kiddie takes legit
things and makes them mine on machines they don't own and everyone is
freaking out because "Omg wtfbbq a miner!!!" JayDDee calls it noob
insurance. Check the tracker before making a new ticket. There is one of
these at least once a week.

**Comment by naviretlav** [comment]
I have tried multiple mining software and found that most of them are not reported as trojan at all, so I believe that there is a way to make it "clean" for the virus checking tools.

**Comment by aaronsace** [comment]
@naviretlav That's not how virus checkers work; Trojans use miners within them and virus checkers do not care about false positives. Please close the issue, thank you.
