### ISSUE TITLE
IPBC

### ISSUE THREAD

**Issue by rplant8** [JayDDee/cpuminer-opt#134]
Thanks for v7, there is one more popular coin IPBC with slightly modified cyptonight-lite-v7. Diff from xmr-stak https://github.com/fireice-uk/xmr-stak/pull/1489/files

**Comment by JayDDee** [comment]
I'm not going to chase all the new cryptonight variants. I did Monero because it's a big coin and
several other coins also use the same variant. Most other variants are for a single coin.

I will either do all of them at once or none at all and only if it requires minimal effort on my part.

What I need for all all variants is:
1. Specifications. Is it a distinct algo or a variant signalled in the data blob (as is cryptonightV7).
2. Sample code or diff compatible with cpuminer.
3. What coins use it and where to test.

These are the variants I am aware of, there nay be others:

cryptonight: original Monero
cryptonightV7: new Monero
cryptonight-heavy: ?
cryptonight-light; original Aeon
cryptonight-lightV7: ?
cryptonight-light-ipbc: IPBC

**Comment by joesixpack** [comment]
cryptonight-heavy: SumoCoin, Loki.  https://github.com/curie-kief/cryptonote-heavy-design

**Comment by JayDDee** [comment]
@joesixpack, very interesting read about the weakness in V7 but not enough detail about the
heavy implementation.

**Comment by JayDDee** [comment]
No further info provided.
