### ISSUE TITLE
adding new CPU algo Yespower

### ISSUE THREAD

**Issue by millerfortie** [JayDDee/cpuminer-opt#156]
Cryply.io 

https://github.com/cryply/yespower

**Comment by Daniel-Medeiros** [comment]
Please add support for yespower algorithm.

**Comment by solardiz** [comment]
Instead of the outdated pre-release version 0.9 that's currently in cryply's repo above, please use the 1.0 release (or whatever is current at the time this issue is worked on):

https://www.openwall.com/yespower/

Also, please replace the existing yescrypt-0.5 code with yespower in `YESPOWER_0_5` compatibility mode. It is fully compatible with what yescrypt-0.5 was, just faster. BTW, with that update there's also no longer a need to rename the SHA-256 files/functions, as the potential clashes have been worked around in the yespower release differently.

**Comment by JayDDee** [comment]
See https://github.com/JayDDee/cpuminer-opt/pull/155
