### ISSUE TITLE
crash on W10 with a Phenom II X6 1075T

### ISSUE THREAD

**Issue by Alysko** [JayDDee/cpuminer-opt#18]
It's a non AES CPU, so I use the legacy version, but it always crash (after setting Stratum difficulty).

**Comment by JayDDee** [comment]
From the release notes:

AMD CPUs older than Piledriver, including Athlon x2 and Phenom II x4, are not
supported by cpuminer-opt due to an incompatible implementation of SSE2 on
these CPUs. Some algos may crash the miner with an invalid instruction.
Users are recommended to use an unoptimized miner such as cpuminer-multi.
