### ISSUE TITLE
Fails to build with `-fno-common` / GCC 10

### ISSUE THREAD

**Issue by candrews** [JayDDee/cpuminer-opt#232]
gcc-10 and above flipped a default from -fcommon to -fno-common: https://gcc.gnu.org/PR85678

cpuminer-opt currently fails to compile when given the CFLAG `-fno-common`

Here's the the build log showing the failure:
[net-p2p cpuminer-opt-3.11.7 20200127-033308.log](https://github.com/JayDDee/cpuminer-opt/files/4118762/net-p2p.cpuminer-opt-3.11.7.20200127-033308.log)

Originally reported at https://bugs.gentoo.org/706666 and here's some more info about how to fix the issue: https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common

**Comment by JayDDee** [comment]
I'm not liking this and I already have a beef with GCC merging functions inappropriately.

The problem as described in the porting notes is with multiple definitions in seperate .c files.
The constants and variables reported as multiply defined are defined only once in a header file
and included in multiple source files.

It's not the same thing and the compiler should be able to figure that out. 
It should only throw an error when there are multiple explicit definitions in source files, not
multiple implicitly included definitions from a single header file. After all header files are intended
for "common" items.

**Comment by JayDDee** [comment]
As it turns out some of the errors are in code that I already had isue with but it's legacy code and
I was hesitant to make any changes without a good reason.

Those changes will eliminate all but one of the errors but it's not as simple as making an
extern declaration.

The last one will need an extern, and also a prudent initializer.

Are you building as a user or is this some kind of official package verification? 
I've never used Gentoo but the log looks like a package build. I wasn't aware Gentoo
included cpuminer-opt in their packages.

The reason I ask is urgency. As a user the workaround is perfectly acceptible even in for
the long term. But for a distribution it may not be so. If this is official what is the impact of the
workaround?

**Comment by candrews** [comment]
I'm reporting this issue as both a user and the Gentoo maintainer of this package - cpuminer-opt is indeed in Gentoo :-) https://packages.gentoo.org/packages/net-p2p/cpuminer-opt

The distro policy is to have packages build with GCC defaults, and since this will be a GCC default with the release of GCC 10, we're trying to get a head start by testing packages and reporting any issues we find.

**Comment by JayDDee** [comment]
"A head start" that's what I like to see. I presume that means no urgency. Is a week ok
for a fix? It will give me a chance to finish what I'm currently working on and do a proper job in the
old code. It may be sooner if thing go well.

**Comment by candrews** [comment]
That would be awesome - thank you! :-)

**Comment by JayDDee** [comment]
I've done all the coding for the GCC 10 issue. In the end, all of the offenders were my onw doing.
2 of them were variables using memory, a good enough reason to declare them extern in the
header file. The others were clumsy atempts to handle vector constants efficiently that begged tto
be rerwitten. I had split the original file while avoiding the rwwrite but also hadn't cleaned up
all the duplication. It was all work that needed to be done, for one reason or another.

Just a few more things to do, it should be released within the next day.

**Comment by JayDDee** [comment]
cpuminer-opt-3.11.8 is released. Please test and report any problems.

I should reconginze your name in the future but feel free to mention your position, it will get my
attention.

**Comment by JayDDee** [comment]
There were other instances of similar code (uncontrolled cloning) but the release only fixed
with the errors reported which only applied to the CPU architecture beingtargetted in the build.
You may get similar multiple definition errors when compiling for other CPU architectures.

The'll all be fixed in the next release.

**Comment by JayDDee** [comment]
cpuminer-opt-3.11.9 is released. Since no problems have been reported with the previous
release I assume it compiled ok. Closing.
