### ISSUE TITLE
API dead since v3.11.9

### ISSUE THREAD

**Issue by RainbowMiner** [JayDDee/cpuminer-opt#235]
Even when using "-b 127.0.0.1:50007", the API doesn't respond, anymore:

`WARNUNG: Could not request from 127.0.0.1:50007`

**Comment by melt7777** [comment]
Thanks for the consistent hard work on this miner, JayDDee... But...ummm...
You disabled API by default and then suggested downgrade as a fix???  WHAT?
Why would you make such a user-unfriendly breaking change, @JayDDee ?? 

~ melt
getpimp.org | miner.farm

Mining coins every day since 2012.

**Comment by JayDDee** [comment]
It works for me with -b 127.0.0.1:5007.

However, the default port 4048 won't work if not specified. That can be easilly fixed but is  it
really a bug?

I don't see any value in defining a default port. The user needs to manually enable the API
now so nothing to include the port. It also helps the user remembber the port number
they defined.

I don't have a strong opinion either way but I'm leaning toward leaving it as is.

@melt7777 

Was that directed at me? I never sggest a downgrade as a "fix" for anything.
And what does powershell have to do with anything?

**Comment by JayDDee** [comment]
Since there appear to be some opinionated people reading i would like some opinions.

Assuming API is disabled by default what is the simplest way to enable it with defaults.

getopts doesn't allow optional arguments so the following it is not possible to use
-b with and without an arguiment.

A seperate option could be used to enable the API to the default address and port

For example:

--api  : enable API with default listnening address
--api-bind: assumes --api and specifies listening address

-b would be still be a short option for --api-bind, there would be no shortcut for --api.

From there it would probabnly be easy to  allow some flexibility with --api-bind:
--api-bind ipaddr:port  (set both ip addr and port)
--api-bind ipaddr          (set ip addr, default port 4048)
--api-bind port              (set port, default ip addr 127.0.0.1)

Another alternative  is to use a keyword to specify the defaults so something like
-b default, or -b on. But I don't see any benefit oin doing it that way. If data is required
then use the real thing not some abstraction.

**Comment by JayDDee** [comment]
I should point out some of my motivation.

I asume the majority of users do not use the API.
Users who do use the API are likely more experienced.
The defaults aren't documented anywhere.
I also assume many APU users also use mining manager programs with configuratin files.
Configuration files should rarely rely on defaults so a well written config shouldn't need to be
changed.

So, my intention is to make the defaults suit the majority and don't oversimplify API usage.
Enabling the API should be a concious decision with specific intent and the user should know
how to connect so putting the address in the argument it trivial.

**Comment by RainbowMiner** [comment]
@JayDDee thank you so much for your effort on the Cpuminer. It has become one of my favorites :)

I do agree 100% with your opinion: the API should be disabled by default. Using "-b"/"--api-bind" should be the trigger to automatically enable the API. So it's just like it is :) What leaves me to the question, why the "-b" didn't work out for me, today. Is it a Windows-only problem, maybe? I didn't try out on Linux, yet.

**Comment by JayDDee** [comment]
I just tested it on Windows and it appears to work. The startup mesage was displayed showing
the API  enabled but I didn't try to connect.

I have no idea why it isn't worikng for you, Tthe API change didn't affect any targetted code.

**Comment by JayDDee** [comment]
On another topic, about Rainbow miner.

I've been looking for a mining manager that works on Linux but hadn't come accros Rainbowminer.

I noticed in the install script that it requires root and installs to the system. I prefer not to install
applications to the system if possible. Can you provide the option to install in a user directory? 
I don't know if Power shell can be installed for a single user but that's another issue.

If I have time I may play with the install script to try.

**Comment by melt7777** [comment]
Hello friends - thank you for the additional information. I can verify the API is working as expected on Ubuntu Linux and I have example command line as `/opt/miners/cpuminer-opt/cpuminer -o stratum+tcp://eu.blockmasters.co:6333 -u 1BTCaddressHere -p c=BTC -a yescryptr16  --api-remote --api-bind 127.0.0.1:4029`

In our testing on PIMP OS 2.15 (latest) (Based on Ubuntu 18.04 LTS) it works as expected. Here is screenshot of startup:

![image](https://user-images.githubusercontent.com/4382542/73795047-af8aa200-4777-11ea-9c25-a80289c86493.png)

Screenshot of miner running: 

![image](https://user-images.githubusercontent.com/4382542/73794957-7eaa6d00-4777-11ea-8ff6-96a1a2505e41.png)

And the API information is being provided to miner.farm properly:

![image](https://user-images.githubusercontent.com/4382542/73795158-f6789780-4777-11ea-9652-839309094687.png)


Thank you very much for your explanations and your attentions. We are thankful for your active development for all these years, JayDDee. We as miners appreciate you and we as fellow developers appreciate you. 

~ melt
getpimp.org | miner.farm
Mining every day since 2012

**Comment by melt7777** [comment]
Hello friends - thank you for the additional information. I can verify the API is working as expected on Ubuntu Linux and I have example command line as `/opt/miners/cpuminer-opt/cpuminer -o stratum+tcp://eu.blockmasters.co:6333 -u 1BTCaddressHere -p c=BTC -a yescryptr16  --api-remote --api-bind 127.0.0.1:4029`

In our testing on PIMP OS 2.15 (latest) (Based on Ubuntu 18.04 LTS) it works as expected. Here is screenshot of startup:


![image](https://user-images.githubusercontent.com/4382542/73795899-c29e7180-4779-11ea-87ad-2f98dc91b53b.png)

And the miner screen looks good, and what API information is available is being provided to miner.farm properly:

![image](https://user-images.githubusercontent.com/4382542/73796340-f1691780-477a-11ea-8424-d87e983e8cb4.png)

Thank you very much for your explanations and your attentions. We are thankful for your active development for all these years, JayDDee. We as miners appreciate you and we as fellow developers appreciate you. 

~ melt
getpimp.org | miner.farm

**Comment by RainbowMiner** [comment]
I re-checked and the API works like a charm, tests with `-b 127.0.0.1:50007`. On both, Linux and on Windows rigs. I think, I done the tests with `-b 50007`, earlier today - and that failed (and still fails) to init the API.

Sorry for having you bothered!

> I've been looking for a mining manager that works on Linux but hadn't come accros Rainbowminer.
>
> I noticed in the install script that it requires root and installs to the system. I prefer not to install
> applications to the system if possible. Can you provide the option to install in a user directory?
> I don't know if Power shell can be installed for a single user but that's another issue.
>
> If I have time I may play with the install script to try.

Oh, that would be nice :) Drop me an issue on my github, if you need assistance. I do currently install powershell plus some common libs to the /opt path. Plus I register a small daemon script (it will execute all overclocking tools and miners as root).

Except from powershell, I can say, that the root is not needed, if you do not plan to use overclocking.
Speaking of powershell, I am not so sure - eventually it may not work, if it's not installed as root.
