### ISSUE TITLE
HODL error

### ISSUE THREAD

**Issue by platinum4** [JayDDee/cpuminer-opt#237]
Hi, please see the bug below:

i7-4790K 32GB RAM

![image](https://user-images.githubusercontent.com/6779241/73867012-7d2a8480-480b-11ea-8112-1ba690f875dc.png)

**Comment by JayDDee** [comment]
I didn't know anyone was still minig hodl. Thanks for reporting. I'll fix it in the next release. 

Please report any other issues with hodl. If you're willing to do some verification testing maybe
I can clean it up a bit.

**Comment by platinum4** [comment]
Sure, let me know please.  Thanks again for your hard work.

**Comment by JayDDee** [comment]
The "BUG" is in the way share results are reported. This may account for the missing share stats
so you  might want to wait for the next release to report other issues.

The invalid share is a concern, do they happen often?

**Comment by platinum4** [comment]
Not sure, the miner closes after that first share, I had to add a pause line to .bat file to catch it before it closed the window.

It happens every 1st share though so it doesn't mine effectively at all.

**Comment by JayDDee** [comment]
You can open a new issue for that or we can track it here. Is there any error message on exit?
A segfault? or just a silent exit?

**Comment by platinum4** [comment]
Silent exit, hang on, how can I enable logging for you on this I can't see it in readme or --help

**Comment by JayDDee** [comment]
I suggest when you identify a problem you go back to older releases to compare. Fining the
release that broke it is 90% of solving the problem. There hasn't been much activity in the hodl
code so you should go back by major releases, then focus in on the minor release.

**Comment by JayDDee** [comment]
Copy /paste is a problem with the command line but if you use the command line directly you can
capture a screenshot of the output.

Just to confirm the problem, do you always get one good share then an invalid share then exit?

**Comment by platinum4** [comment]
Confirm yes
![image](https://user-images.githubusercontent.com/6779241/73870464-bc5bd400-4811-11ea-93de-13ebb8a52775.png)

**Comment by platinum4** [comment]
I'm trying v3.9.5.3 right now

**Comment by JayDDee** [comment]
I hadn't noticed the multiple unconfirmed submits before. That could be a server or networking issue.

You should note the older releases will have different output, the focus should be on the share
results and the silent exit, not the messages. Silent exits is the worst kind because there are
no clues.

**Comment by platinum4** [comment]
Yeah I know, v3.9.5.3 does not exit, look below
![image](https://user-images.githubusercontent.com/6779241/73871220-19a45500-4813-11ea-87a7-e426f75563f2.png)
![image](https://user-images.githubusercontent.com/6779241/73871258-29239e00-4813-11ea-87ca-f186f29b2d83.png)

**Comment by platinum4** [comment]
`cpuminer-avx2 -a hodl -o stratum+tcp://hodl.optiminer.pl:5555 -u HFX3N3DZKMjsJsRTwfAgq4iqoCSNh12Qfb -p x -D
pause`

**Comment by JayDDee** [comment]
Looks like 2 sepertate problems (3 with the "BUG").

1. Invalid shares since before v3.9.5.3. (suggest testing 3.8.8.1)

2. Silent exit after v3.9.5.3.

Both are show stoppers. The replies are slow but appear to arrive eventually, you just don't see
them when the program crashes before they arrive.

**Comment by platinum4** [comment]
v3.8.8.1 works 
![image](https://user-images.githubusercontent.com/6779241/73872058-9b48b280-4814-11ea-9c5f-95b7963fa5c7.png)

**Comment by platinum4** [comment]
v3.9.4 works
![image](https://user-images.githubusercontent.com/6779241/73872205-dfd44e00-4814-11ea-94fd-764893f9bceb.png)

**Comment by JayDDee** [comment]
You can ignore much of my previous post. You don't need to test with another miner if you find a
working version of cpuminer-opt.

I still don't understand how the miner could produce the pattern but when the exact release is
identified I'll have somewhere to look.

**Comment by platinum4** [comment]
v3.9.5.2 appears to not work; look at how it is receiving jobs
![image](https://user-images.githubusercontent.com/6779241/73872566-891b4400-4815-11ea-92c6-38e123095afd.png)

**Comment by platinum4** [comment]
`job -1` seems to be the issue I would be guessing.

**Comment by platinum4** [comment]
Same `job -1` on v3.9.5.1
![image](https://user-images.githubusercontent.com/6779241/73872679-c2ec4a80-4815-11ea-8d90-483e658e1021.png)

**Comment by platinum4** [comment]
`job -1` v3.9.5
![image](https://user-images.githubusercontent.com/6779241/73872741-e57e6380-4815-11ea-8e9a-4309b5e76c87.png)

**Comment by platinum4** [comment]
v3.9.4 is the last version that worked with `-a hodl` if you get a chance to check this out that'd be great dude.

**Comment by platinum4** [comment]
Even the miner loader has mentioned this has been a problem for a bit
![image](https://user-images.githubusercontent.com/6779241/73872917-39894800-4816-11ea-9821-7ff49afb53b2.png)

**Comment by JayDDee** [comment]
I don't understand your last post, what's a miner loader?

Thanks for the good work, I now have a lead I can follow up.

**Comment by platinum4** [comment]
Powershell script for the miner in a multiminer, anyhow, I think it happened during restructuring from v3.9.4 to v3.9.5

**Comment by JayDDee** [comment]
I've reproduced the problem exactly on Linux except for the silent exit., Linux keeps hashing.
V3.9.5 was a big release with big changes to hodl and core code.

**Comment by platinum4** [comment]
Thanks buddy, I'm sure once you get it fixed there when it's compiled to Windows it should be fine.

**Comment by JayDDee** [comment]
I think I understand the crash, the jobid is too long and causes a buffer overflow when submitting
a share.

I also have a fix for the "BUG" .  It now shows some share stats but not all.

But I still get the burst of submits followed by one accepted and the rest rejected.
That is a very strange pattern that will require some time to think about what could cause it.

The goal is to get the shares working and live with whatever stats issue remain as they are
specific to hodl and likely due to the hodl stratum not providing the data.

If I don't have a solution for the rejects soon I will release what I have ( I was getting ready
for a release when you reported the issue) and then look deeper into hodl. You wojuld be able to
confirm the crash was fixed on Windows, if nothing else.

The excessive messages is a problem but a low priority.

**Comment by platinum4** [comment]
Sure, I am willing to test whatever if you need it, not sure if you have a version history between 3.9.5 and 3.9.4

**Comment by JayDDee** [comment]
Oh yes I have the version history, 4 snapshots between 3.9.4 and 3.9.5 but there's nothing
obvious that changed. Hodl code didn't really change just a small administrative change.
It appears hodl was a victim of changes to code that's used by all algos but only Hodl broke.

**Comment by JayDDee** [comment]
With some stats now working I can see what appears to be submitting the same share over and
over again, the share diff is exactly the same for all shares in the burst.

**Comment by JayDDee** [comment]
This is going to be difficult.

I have seen the same share submitted by multiple threads and the same share submitted
multiple times by the same thread. Both should be impossible.

The only change to hodl code was an interface change that required the same code change
for every other algo as well with no ill effects.

The major change in v3.9.5 was the introduction of statistics. The stats are gathered in mining
functions but should not interfere with mining in any way. again it affects all algos and only Hodl
broke.

The crash is believed to have been caused by a job id that was longer than the buffer. This was the
result of tracking job ids as part of the stats feature. So it is possible for the stats code to 
indirectly affect mining.

At this point my only lead is to follow up with the job id to see if there are other places it
could overflow a buffer. This would corrupt data and result in unexplainable behaviour and
we certainly have unexplainable behaviour. It would also explain why hodl broke with no
significant changes to its code.The excessively long job id may the the nexus.

I'm going to go agead with the next release and pick up this issue afterwards when I can focus
a little better.

In the upcoming release you should (hopefully) expect the following:

- silent crash is solved
- stats should mostly work
- job id is truncated in share result log (to prevent the crash)

The fix for the rejects will hopefuly be in the following release.

**Comment by platinum4** [comment]
You're good dude, as you mentioned, I'm probably the only person on earth trying to mine this at the moment.

**Comment by JayDDee** [comment]
LOL. I've considered just saying use the old version, and it may eventually come to that but I'm
not ready to give up yet.

**Comment by platinum4** [comment]
No problem maybe a fresh set of eyes after the sun has moved around might help

**Comment by JayDDee** [comment]
Have you tried v3.12.0 yet?

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/73951220-d4d7f700-48c2-11ea-8971-5970a0d72b20.png)

**Comment by JayDDee** [comment]
Did it crash?

**Comment by platinum4** [comment]
Yes you can see it exit to DOS prompt due to a crash after that first attempt at a share.

**Comment by JayDDee** [comment]
It's better if you don't use a bat file for testing, especially when debugging a crash or silent exit.

So, it still crashes. That means I fixed a different crash. This is a step backward.

I'm going to have to take a different approach. I'll ignore the crash fo now and focus on the changes
in 3.9.5 that broke it. I'll try removing some of that new code to see if I can fix the rejects
without breaking anything else. If I can identify what code broke it I can figure out why.

**Comment by JayDDee** [comment]
Fixed it!

It was a stupid error in hodl code, I used the type instead of the variable name in a function
call. I have no idea why it compiled but that bug explains why every thread was trying to submit
the same hash.

The stats also work. The only remaining issue I see is the repeated job logs. That is for another day.
I'll be releasing the reject fix soon.

There is also the delayed replies but that's not a miner issue.

**Comment by JayDDee** [comment]
The repeated job logs may not be fixed. The problem is unique to hodl but the solution would
affect performance of all algos. The fix is to compare the job ids before displayig the log but
that involves an expensive string comparison in code used by all algos.

**Comment by platinum4** [comment]
Isn't it fun to hunt down a genuine problem every now and again, thanks so much for your effort dude!

**Comment by JayDDee** [comment]
But I'm pissed the compiler didn't catch it. The arg is supposed to be a variable of the type,
not the type itself. It should have been a compile error.

**Comment by platinum4** [comment]
I agree based on the coding I did in seventh grade what you are saying makes sense if it should not have been passable I don't see how it compiled.

**Comment by JayDDee** [comment]
cpuminer-opt-3.12.0.1 is released. Please test and report any problems.

**Comment by platinum4** [comment]
Looking good my dude, seems to be accepting shares as normal.  Thanks again!
