### ISSUE TITLE
Question to Xeon mining

### ISSUE THREAD

**Issue by iUNeIV** [JayDDee/cpuminer-opt#289]
Hi,

I would like to know if Xeon Phi CPUs are compatible with mining software? I know he uses AVX512 in these CPUs?
Also, Is it also functional with software: Intel Xeon Phi 5110P
Good day!

**Comment by JayDDee** [comment]
It's not supported so YMMV.

I haven't been following Phi because it's not good for mining, particularly memory hard CPU algos.
AVX512 support in cpuminer-opt requires AVX512F, AVX512VL, AVX512DQ & AVX512BW.
As far as I know Phi doesn't comply.

I don't know anything about the Phi software environment so you're on your own.

If you have one give it a try and post your results.

**Comment by YetAnotherRussian** [comment]
> I would like to know if Xeon Phi CPUs are compatible with mining software?

Use the special one - https://lukminer.org

Also cpuminer-opt works okay on rare desktop CPU's like Xeon Phi 7250 or 7290, but these are slow as heck for the price (somewhere near E5-2620, or even less). True waste of time & money (cheap CPUs, but very rare and expensive motherboards).

**Comment by JayDDee** [comment]
I'm closing this. Author hasn't followed up for a week so I assume they've lost interest. 
If Phi requires a "special" miner it's even less useful as a mining platform.
There's no chance I will ever support it.

**Comment by ps2chiper** [comment]
It is because they are liquidating Intel Phi 5110p cards on ebay for 40 dollars each. If there is any way to profit off of these cards, it may be worth while.
