### ISSUE TITLE
Question to missing hashrate

### ISSUE THREAD

**Issue by benediktwetzel** [JayDDee/cpuminer-opt#304]
Hi, this is a really nice work!

However, unfortunately, it seems that it does not generate hashes while my CPU is running at ~100%.

I have tried `SHA256`, `SCRYPT` and `QUARK` and use Docker to run it. 

To run, for example, with `QUARK` I use the following command:
```bash
docker run -it --rm cpuminer-opt:latest -a quark -o stratum+tcp://quark.eu-west.nicehash.com:3345 -u 3AnW7M1E8rLFRNrrzjYah67vFy5XdSdgxz -p x -t 3
```
The periodic report displays the following: 

```log
[2021-03-24 21:57:02] quark: quark.eu-west.nicehash.com:3345
                      Periodic report 1m23s 6m01s
                      Share rate 0.00/min 0.00/min
                      Hash rate 0.00h/s 0.00h/s (506.68kh/s)
                      Submitted 0 0
                      Accepted 0 0 -nan%
                      Hi/Lo share diff 0 / 9e+99
```

What I am doing wrong?
Good day!

**Comment by JayDDee** [comment]
It's hashing quark at 506.68kh/s but that's not enough to find shares. The effective hash rate is zero because no
shares were submitted. The pool will also report zero for the same reason.

You need an ASIC miner for these algos. Look at the share TTF in the New Block log, it should give you a clue whether
your CPU can be expected to find shares on a regular basis. If share TTF is more than 5 minutes you are likely to have
stratum disconnects also.

Stratum difficulty also affects share rate. Some pools automatically adjust stratum difficulty but there is a limit.
For some algos even the lowest permitted difficulty isn't low enough for a CPU.

**Comment by benediktwetzel** [comment]
Thank you!
