### ISSUE TITLE
need help for add Opencl and run miner on vitis

### ISSUE THREAD

**Issue by jackwatson01234** [JayDDee/cpuminer-opt#308]
Hi, first of all, thank you for improving this app.
My question is about the hash rate of the program compared to Verthashminer. I run the code on Intel 9900k processor and got 41 kh/s in Verthashminer. In Cpuminer this value reaches 18 kh/s . What is the reason for this difference?

**Comment by JayDDee** [comment]
The CPU has an integrated GPU so it's effectively 2 devices requiring different mining software for each.
Verthash miner is using the iGPU and cpuminer is using the CPU.
You can probably run both simultaneously but because they share memory, and memory is the bottleneck,
you likely won't get near the sum of both individually.

Please post the Verthash logs so I can confirm

**Comment by JayDDee** [comment]
A simpler explanation for your question is Verthash is a GPU miner and cpuminer-opt is a CPU miner.
Vitis is an FPGA and has nothing to do with either.

**Comment by jackwatson01234** [comment]
> A simpler explanation for your question is Verthash is a GPU miner and cpuminer-opt is a CPU miner.
> Vitis is an FPGA and has nothing to do with either.

Ty for your answer, 
actually, I found new futures Xilinx Runtime that can help to deploy OpenCL application on Xilinx FPGA, now Im trying to use your app or Verthashminer to run on it.  the problem is when I wanna build Verthash on Vitis, it need to create makefile from Cmakelist.txt and many of library and files not included in created makfile. 
so now I wanna use your code and rewrite it to make runnable in Vitis.(Im newbie and hope to gods help me :) )
