### ISSUE TITLE
Low performance

### ISSUE THREAD

**Issue by gvgit** [JayDDee/cpuminer-opt#31]
Hi, I'm running cpuminer-opt with command `./cpuminer --algo=cryptonight --url=stratum+tcp://cryptonight.eu.nicehash.com:3355 --userpass=XXXX:x -t 31` on a machine with around 450 H/s. But with another pool and xmr-stak-cpu I got 750H/s as expected.

Why is my hashrate lower than it is with xmr-stak-cpu?

Regards

**Comment by JayDDee** [comment]
Stak is faster but there shouldn't be that much difference. I need more info about your CPU,
as well as the miner's startup info showing the available features.

Stak uses huge pages, an OS feature that improves memory performance for large data.
I have not implemented huge pages in cpuminer-opt because there are side effects:
- requires OS tweaking
- need to run app as admin on Windows
- increased memory fragmentation
- apps need to be modified to use huge pages
- can reduce performance in some circumstances

Huge pages is better suited to server grade systems with lots of RAM and cache than  typical
desktop PCs.

The feature is not yet mature in my opinion. It should be enabled by default in the OS and
fully transparent to the app.

Regardless, huge pages shouldn't make that much of a difference. If you provide more info
I will look into it further.

**Comment by JayDDee** [comment]
No further information provided.

**Comment by maxfunky** [comment]
Could Huge pages be added as an option ?
