### ISSUE TITLE
How to use the api ?

### ISSUE THREAD

**Issue by iangregsondev** [JayDDee/cpuminer-opt#335]
Hi,

I am using a really outdated cpuminer and found this :-)

One thing that really interests me is that this appears to have an API, but I am unable to find any documentation of how to use it.

It would be nice to be able to interrogate the cpuminer via an API and also maybe receive updates of when the miner disconnects or things of that nature..

Is there some API docs of how to use it 

Thanks.

**Comment by JayDDee** [comment]
It jus has a simple tcp socket, imported from cpuminer-multi. A simple telnet connection will work. Telnet to the port
and type help for a list of avalaible commands, it's a very short list.

I've neglected the API because it competes with hashing on the CPU. GPU miners don't have that problem and can
support more sophisticated API.
