### ISSUE TITLE
is it possible to test mining Kadena (Blake2s) with cpuminer-opt ? 

### ISSUE THREAD

**Issue by developeralgo8888** [JayDDee/cpuminer-opt#352]
i am just testing how to mine Kadena (Blake2s) with cpuminer-opt  through poolflare pool. What is the correct command on Linux (ubuntu 20.04) to use ?  I am getting segmentation fault error . The cpuminer build from the source was fine with no errors. I am missing something ?

below is the example i am using to test

`./cpuminer -a blake2s -o stratum+tcp://kda-us.ss.poolflare.net:443  -u k:ac3a4dac6a15c48b842886e615a35ed90e747d8da6b593712b964862e2852739 -p x  -t 10 --cpu-affinity 10`

```
CPU: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
SW built on Dec  7 2021 with GCC 9.3.0
CPU features:  AVX2    AES
SW features:   AVX2    AES
Algo features: AVX512

Starting miner with AVX2...

[2021-12-07 03:04:59] CPU affinity [..!.!...................................................]
[2021-12-07 03:04:59] Stratum connect kda-us.ss.poolflare.net:443
[2021-12-07 03:04:59] 20 of 56 miner threads started using 'blake2s' algorithm
[2021-12-07 03:04:59] Stratum extranonce1= a084, extranonce2 size= 6
[2021-12-07 03:04:59] Stratum answer id is not correct!
[2021-12-07 03:04:59] Stratum connection established
[2021-12-07 03:05:00] CPU temp: curr 35 C max 0, Freq: 1.197/2.595 GHz
Segmentation fault (core dumped)
```

**Comment by JayDDee** [comment]
I did a quick test of blake2s on zergpool, no problems.
Based on the stratum warning I suspect a stratum issue. Based on the pool port number being HTTPS I suspect a secure
protocol is required for this pool. You could try "https:" or "stratum+tcps:" instead of "stratum+tcp:" to see if that works.
I also noticed you're misusing the cpu-affinity option. It's a bit mask not a number so 10 will only use 2 cores for all 10 threads.
It's not necessary in most cases anyway.

**Comment by JayDDee** [comment]
It appears that either the coin or the pool uses a different stratum protocol that not supported by cpuminer-opt.
You could try a different pool but if that doesn't work it looks like the answer is no.
