### ISSUE TITLE
add support for Yilacoin (YCN): sha3d

### ISSUE THREAD

**Issue by JayBitron** [JayDDee/cpuminer-opt#360]
Hello,

I'm the developer of Yilacoin, I gave cpuminer link for users who wants to use for stratum protocol which I use and it's perfectly fine, but people are willing to use GBT protocol, see: https://bitcointalk.org/index.php?topic=5381689.msg59012262#msg59012262

**Comment by JayDDee** [comment]
GBT support is hit and miss. New coins that use variations of the protocol are likely not going to work because I don't know how. I also don't have the ability to try to support every coin using a new twist, testing would be impossible. The miner would also get overly bloated.

If you have a working GBT client I suggest you fork cpuminer-opt and make a custom miner for your coin.

**Comment by JayBitron** [comment]
It's using the same protocol like bitcoin, only transaction hashes including merkle root, block hash and pow hash are calculated using sha3d, everything else is the same as bitcoin.

Thanks anyway.

**Comment by JayDDee** [comment]
It must be something else because cpuminer-opt already handles sha3d merke root, it works on stratum.
Bitcoin has probably updated GBT and cpuminer-opt is no longer compliant. The bottom line is I don't have the solution.
