### ISSUE TITLE
Using algo/keccak as keccak256 library

### ISSUE THREAD

**Issue by t-anyu** [JayDDee/cpuminer-opt#388]
Hey,

How can I use algo/keccak (AVX2, AVX512 optimized) for my own project? I need to hash arbitrary length bytes.

Btw. what does 4-way and 8-way keccak mean?

Thanks

**Comment by JayDDee** [comment]
N-way is the number of data threads per CPU thread, it's only usefull for parallel hashing of multiple data streams.
If  you don't need parallel hashing you should use an existing library like SPH. Also if you need security don't use any of my code.
Arbitrary length may not work with my code, some optimizations assume certain lengths. Otherwise read the code to figure it out.
