### ISSUE TITLE
Mining via RPC

### ISSUE THREAD

**Issue by joesixpack** [JayDDee/cpuminer-opt#40]
The RPC support to solo mine to a local node appears to be broken.  No amount of command switches will make it work, including --no-stratum.  Other miners work fine out of the box.

**Comment by JayDDee** [comment]
Getwork mining is still a work in progress. Some algos have been reported to work but others are
unknown. I need more info specifically the algo and the miner output with --debug.
It would also help if you tell me which specific miners work.

Make sure you include http:// prefix in the url, otherwise it defaults to stratum+tcp://.

**Comment by joesixpack** [comment]
> Make sure you include http:// prefix in the url, otherwise it defaults to stratum+tcp://.

That was the problem.  Thanks!

**Comment by JayDDee** [comment]
Nice to see it was something simple. Can you tell me which algo it is so I
can add it to the known working list.?

**Comment by joesixpack** [comment]
JHA
