### ISSUE TITLE
scrypt:N (1048576 , veriumReserve) optimizations broke

### ISSUE THREAD

**Issue by darkwolfultima** [JayDDee/cpuminer-opt#73]
in version 3.8 when mining Verium, no optimizations are displayed or implemented. hashrate suffers.

```
         **********  cpuminer-opt 3.8.0  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU: Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz.
SW built on Jan 25 2018 with GCC 7.2.0.
CPU features: SSE2 AES.
SW features: SSE2 AES.
Algo features: None.
Start mining with no optimizations.
```

tested all version between 3.6.5 and 3.8
SSE , AES optimizations are implemented and working in versions:

```
        **********  cpuminer-opt 3.7.4  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT
     Forked from TPruvot's cpuminer-multi with credits
     to Lucas Jones, elmad, palmd, djm34, pooler, ig0tik3d,
     Wolf0, Jeff Garzik and Optiminer.

CPU: Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz
CPU features: SSE2 AES
SW built on Jan 25 2018 with GCC 7.2.0
SW features: SSE2 AES
Algo features: SSE2
Start mining with SSE2
```

```
         **********  cpuminer-opt 3.6.5  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT
     Forked from TPruvot's cpuminer-multi with credits
     to Lucas Jones, elmad, palmd, djm34, pooler, ig0tik3d,
     Wolf0, Jeff Garzik and Optiminer.

CPU: Intel(R) Xeon(R) CPU           L5640  @ 2.27GHz
CPU features: SSE2 AES
SW built on Jan 25 2018 with GCC 7.2.0
SW features: SSE2 AES
Algo features: SSE2
Start mining with SSE2
```

please investigate
would like this to work to take advantage of latest statistical information and general code updates also scrypt:N should have avx and avx2 optimizations. havent dug into the code to check.

**Comment by nicklemarr** [comment]
I follow @JayDDee just for his responses to bug tracker tickets lol Let's see how he responds to that one.

**Comment by JayDDee** [comment]
I wonder why I get the sense I'm being trolled.  This seems like a test to see if I can find all the
errors. Should I start with the unsubstantiated claim you made or that you want to use AVX and
AVX2 on a CPU that supports neither? 

On the more serious side, since other people seem to be reading this, there was a change in
how features were listed for algos. Previously all algos reported having SSE2 by default. 
Now they report no optimizations unless I have confirmed they exist and are enabled.
The reporting of algo features does not affect the hash rate in any way. If they really existed
before they still do regardless of how they are reported.

I'll get to fixing them all eventually but I have other priorities for the foreseeable future.

CPU and SW features are actual specifications provided by the CPU and compiler respectively.

If I get any more nonsensical issue reports like this I'll just close them without comment.
