### ISSUE TITLE
Ryzen 7 1800x pc crashes

### ISSUE THREAD

**Issue by seiterseiter** [JayDDee/cpuminer-opt#92]
Hello, im running a Ryzen 7 1800x with no overclock and is completly stable mining cryptonight with xmr-stak. I wanted to start mining lyra2z with cpuminer but for some reason it actually crashes my pc. I tried all 5 bineries but they all crashed with no log or reason why.

I run Windows 10 64bit, Ryzen 7 1800x, GTX 1070.

Could I be doing something wrong?
Thanks :)

**Comment by JayDDee** [comment]
If you're using your mouse you're doing something wrong.

First I don't believe it actually crashes your PC, That's never hasppened before and if it did you
have a serious problem with your PC.

I don't believe it crashed the miner either. There is probably an error on the command line and the
miner exitted and Windows conveniently closed the window to you couldn't see the error.

Windows users should learn how to use the command line before using cpuminer-opt.

**Comment by seiterseiter** [comment]
I dont understand what you mean by using a mouse?

Also I do know how to use the command line. My PC literally shuts down, all fans stop spinning and all LEDs turn off.
Window event viewer just calls it a critical error saying that my system rebooted without cleany shutting down.
I have attached a log of the miner starting before it crashes and also my script that starts the miner.


[start.txt](https://github.com/JayDDee/cpuminer-opt/files/1750488/start.txt)
[log.txt](https://github.com/JayDDee/cpuminer-opt/files/1750489/log.txt)

**Comment by JayDDee** [comment]
Due to the lack of information in your initial report I assumed you were
using a bat file and the window was closing
so you couldn't see the error message. You wouldn't believe how many are
that clueless. I assumed you were one of them.

The key to your problem is the PC shuts down. That has never been reported
by anyone using cpuminer-opt. It's a hardware
issue, possibly overheated. Could also be a hardware fault. With Linux you
can set a temp limit in cpuminer, unfortunately
not available on windows.

Looking at your log file I'd say it didn't have time to get hot, it only
started 2 threads before it crashed (I assume you were
trying to run more than that). PSU problem seems more likely, possibly RAM.
You could run a memtest or some
cpu intensive test program.

**Comment by seiterseiter** [comment]
Sorry about the lack of information, ill remember for next time to post logs.

Its only ever crashed with cpuminer-opt though, I usually have it mining cryptonight and its temperature stays about 55 to 60 digrees Celsius. So my hardware seems fine from using other miners, I guess ill just do some trouble shooting with other algorithims and see if its only doing it for lyra2z

**Comment by JayDDee** [comment]
Cryptonight runs cooler than other algos because the CPU is I/O bound.
